// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SquaresApp.Data.Context;

namespace SquaresApp.Data.Migrations
{
    [DbContext(typeof(SquaresAppDBContext))]
    [Migration("20210603072545_added_point_configuration")]
    partial class added_point_configuration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SquaresApp.Domain.Models.Point", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Points_Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("TDX_Point_UserId");

                    b.HasIndex("UserId", "X", "Y")
                        .IsUnique()
                        .HasDatabaseName("TDX_Point_UserId_X_Y");

                    b.ToTable("Points");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            UserId = 1L,
                            X = -1,
                            Y = 1
                        },
                        new
                        {
                            Id = 2L,
                            UserId = 1L,
                            X = 1,
                            Y = -1
                        },
                        new
                        {
                            Id = 3L,
                            UserId = 1L,
                            X = 1,
                            Y = 1
                        },
                        new
                        {
                            Id = 4L,
                            UserId = 1L,
                            X = -1,
                            Y = -1
                        },
                        new
                        {
                            Id = 5L,
                            UserId = 2L,
                            X = -1,
                            Y = 1
                        },
                        new
                        {
                            Id = 6L,
                            UserId = 2L,
                            X = 1,
                            Y = -1
                        },
                        new
                        {
                            Id = 7L,
                            UserId = 2L,
                            X = 1,
                            Y = 1
                        },
                        new
                        {
                            Id = 8L,
                            UserId = 2L,
                            X = -1,
                            Y = -1
                        });
                });

            modelBuilder.Entity("SquaresApp.Domain.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_User_Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("TDX_User_Username");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Password = "c1c224b03cd9bc7b6a86d77f5dace40191766c485cd55dc48caf9ac873335d6f",
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2L,
                            Password = "b512d97e7cbf97c273e4db073bbb547aa65a84589227f8f3d9e4a72b9372a24d",
                            Username = "User"
                        });
                });

            modelBuilder.Entity("SquaresApp.Domain.Models.Point", b =>
                {
                    b.HasOne("SquaresApp.Domain.Models.User", "User")
                        .WithMany("Points")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SquaresApp.Domain.Models.User", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
